<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ffpi_nodecounter"
 *
 * Auto generated by Extension Builder 2016-07-17
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Nodecounter',
    'description' => 'Counts Freifunk nodes',
    'category' => 'plugin',
    'author' => 'Kevin Quiatkowski',
    'author_email' => 'kevin@pinneberg.freifunk.net',
    'state' => 'stable',
    'version' => '2.2.1',
    'constraints' => [
        'depends' => [
            'typo3' => '10.0.0-11.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
